export const ESSAY_LIST_REQUEST = 'ESSAY_LIST_REQUEST';
export const ESSAY_LIST_SUCCESS = 'ESSAY_LIST_SUCCESS';
export const ESSAY_LIST_FAIL = 'ESSAY_LIST_FAIL';

export const ESSAY_CREATE_REQUEST = 'ESSAY_CREATE_REQUEST';
export const ESSAY_CREATE_SUCCESS = 'ESSAY_CREATE_SUCCESS';
export const ESSAY_CREATE_FAIL = 'ESSAY_CREATE_FAIL';
export const ESSAY_CREATE_RESET ='ESSAY_CREATE_RESET';

export const ESSAY_DELETE_REQUEST ='ESSAY_DELETE_REQUEST';
export const ESSAY_DELETE_SUCCESS ='ESSAY_DELETE_SUCCESS';
export const ESSAY_DELETE_FAIL ='ESSAY_DELETE_FAIL';
export const ESSAY_DELETE_RESET ='ESSAY_DELETE_RESET';

export const ESSAY_DELETE_SOFT_REQUEST = 'ESSAY_DELETE_SOFT_REQUEST';
export const ESSAY_DELETE_SOFT_SUCCESS = 'ESSAY_DELETE_SOFT_SUCCESS';
export const ESSAY_DELETE_SOFT_FAIL = 'ESSAY_DELETE_SOFT_FAIL';
export const ESSAY_DELETE_SOFT_RESET ='ESSAY_DELETE_SOFT_RESET';

export const ESSAY_DELETE_LIST_TRARH_REQUEST = 'ESSAY_DELETE_LIST_TRARH_REQUEST';
export const ESSAY_DELETE_LIST_TRARH_SUCCESS = 'ESSAY_DELETE_LIST_TRARH_SUCCESS';
export const ESSAY_DELETE_LIST_TRARH_FAIL = 'ESSAY_DELETE_LIST_TRARH_FAIL';

export const ESSAY_DELETE_RESTORE_REQUEST = 'ESSAY_DELETE_RESTORE_REQUEST';
export const ESSAY_DELETE_RESTORE_SUCCESS = 'ESSAY_DELETE_RESTORE_SUCCESS';
export const ESSAY_DELETE_RESTORE_FAIL = 'ESSAY_DELETE_RESTORE_FAIL';
export const ESSAY_DELETE_RESTORE_RESET ='ESSAY_DELETE_RESTORE_RESET';

export const ESSAY_DELETE_FORCE_REQUEST = 'ESSAY_DELETE_FORCE_REQUEST';
export const ESSAY_DELETE_FORCE_SUCCESS = 'ESSAY_DELETE_FORCE_SUCCESS';
export const ESSAY_DELETE_FORCE_FAIL = 'ESSAY_DELETE_FORCE_FAIL';
export const ESSAY_DELETE_FORCE_RESET ='ESSAY_DELETE_FORCE_RESET';

export const ESSAY_DETAILS_REQUEST = 'ESSAY_DETAILS_REQUEST';
export const ESSAY_DETAILS_SUCCESS = 'ESSAY_DETAILS_SUCCESS';
export const ESSAY_DETAILS_FAIL = 'ESSAY_DETAILS_FAIL';

export const ESSAY_UPDATE_REQUEST = 'ESSAY_UPDATE_REQUEST';
export const ESSAY_UPDATE_SUCCESS = 'ESSAY_UPDATE_SUCCESS';
export const ESSAY_UPDATE_FAIL = 'ESSAY_UPDATE_FAIL';
export const ESSAY_UPDATE_RESET ='ESSAY_UPDATE_RESET';

export const ESSAY_BROWSE_REQUEST = 'ESSAY_BROWSE_REQUEST';
export const ESSAY_BROWSE_SUCCESS = 'ESSAY_BROWSE_SUCCESS';
export const ESSAY_BROWSE_FAIL = 'ESSAY_BROWSE_FAIL';


export const ESSAY_HIDE_REQUEST ='ESSAY_HIDE_REQUEST';
export const ESSAY_HIDE_SUCCESS ='ESSAY_HIDE_SUCCESS';
export const ESSAY_HIDE_FAIL ='ESSAY_HIDE_FAIL';

export const ESSAY_COIN_CREATE_SUCCESS ='ESSAY_COIN_CREATE_SUCCESS';
export const ESSAY_COIN_CREATE_FAIL ='ESSAY_COIN_CREATE_FAIL';
export const ESSAY_COIN_CREATE_RESET ='ESSAY_COIN_CREATE_RESET';
